mode:
  develop: false   #为true是开启日志



server:
  port: 8090      #路由监听端口



db:
  dsn: root:root@tcp(127.0.0.1:3306)/go_web?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConn: 10 #最大空闲连接数
  setMaxOpenConn: 10 #最多打开连接数



log:
  MaxSize: 1      # 日志文件的最大尺寸（M），超出尺寸后自动分割
  MaxBackups: 10  # 保留旧文件的最大个数
  MaxAge: 90      # 保留旧文件的最大天数