info:
  contact: {}
  title: Go-web开发记录
  version: "0.1"
paths:
  /public/user/login:
    post:
      description: '"用户登录详情"'
      parameters:
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: passwd
        required: true
        type: string
      responses:
        "200":
          description: 登录成功
          schema:
            type: string
        "401":
          description: 登录失败
          schema:
            type: string
      summary: 用户登录
swagger: "2.0"
